# AI Ensemble System for k3s
# Deploy with: kubectl apply -f ai-ensemble.yaml

---
# Promptimizer (Granite 4 350m model)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promptimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promptimizer
  template:
    metadata:
      labels:
        app: promptimizer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: promptimizer
        image: sebastein/promptimizer:v3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: promptimizer
spec:
  selector:
    app: promptimizer
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# LLaMA 3.2 1B model
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: llama
        image: sebastein/llama:v3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: llama
spec:
  selector:
    app: llama
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# Qwen 2.5 Coder 1.5B model
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen
  template:
    metadata:
      labels:
        app: qwen
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: qwen
        image: sebastein/ollama-qwen:v3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qwen
spec:
  selector:
    app: qwen
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# Qwen 3 0.6B model (Smallest)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-small
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen-small
  template:
    metadata:
      labels:
        app: qwen-small
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: qwen-small
        image: sebastein/qwen_small:v3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "800Mi"
            cpu: "300m"
          limits:
            memory: "4Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-small
spec:
  selector:
    app: qwen-small
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# Judge (Gemma 3 1B model)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge
  template:
    metadata:
      labels:
        app: judge
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: judge
        image: sebastein/judge:v3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: judge
spec:
  selector:
    app: judge
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# Orchestrator (Gorkheavy)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      restartPolicy: Always
      initContainers:
      - name: wait-for-services
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          echo "Waiting for services to be ready..."
          until curl -f http://promptimizer:11434/api/tags; do echo "Waiting for promptimizer..."; sleep 2; done
          until curl -f http://llama:11434/api/tags; do echo "Waiting for llama..."; sleep 2; done
          until curl -f http://qwen:11434/api/tags; do echo "Waiting for qwen..."; sleep 2; done
          until curl -f http://qwen-small:11434/api/tags; do echo "Waiting for qwen-small..."; sleep 2; done
          until curl -f http://judge:11434/api/tags; do echo "Waiting for judge..."; sleep 2; done
          echo "All services ready!"
      containers:
      - name: orchestrator
        image: sebastein/gorkheavy_script:v3.0
        imagePullPolicy: Always
        stdin: true
        tty: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
