apiVersion: apps/v1
kind: Deployment
metadata:
  name: promptimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promptimizer
  template:
    metadata:
      labels:
        app: promptimizer
    spec:
      containers:
      - name: promptimizer
        image: sebastein/ollama-promptimizer:v1.0
        ports:
        - containerPort: 11434
        resources:
          limits:
            memory: "1.5Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: promptimizer-service
spec:
  selector:
    app: promptimizer
  ports:
  - port: 11434
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      containers:
      - name: llama
        image: sebastein/ollama-llama:v1.0
        ports:
        - containerPort: 11434
        resources:
          limits:
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: llama-service
spec:
  selector:
    app: llama
  ports:
  - port: 11434
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen
  template:
    metadata:
      labels:
        app: qwen
    spec:
      containers:
      - name: qwen
        image: sebastein/ollama-qwen:v1.0
        ports:
        - containerPort: 11434
        resources:
          limits:
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-service
spec:
  selector:
    app: qwen
  ports:
  - port: 11434
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-small
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen-small
  template:
    metadata:
      labels:
        app: qwen-small
    spec:
      containers:
      - name: qwen-small
        image: sebastein/ollama-qwen_small:v1.0
        ports:
        - containerPort: 11434
        resources:
          limits:
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-small-service
spec:
  selector:
    app: qwen-small
  ports:
  - port: 11434
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge
  template:
    metadata:
      labels:
        app: judge
    spec:
      containers:
      - name: judge
        image: sebastein/ollama-judge:v1.0
        ports:
        - containerPort: 11434
        resources:
          limits:
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: judge-service
spec:
  selector:
    app: judge
  ports:
  - port: 11434
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: sebastein/ai-project:orchestrator
        stdin: true
        tty: true
        resources:
          limits:
            memory: "512Mi"
---