FROM python:3.11-slim

RUN apt update -y && \
    apt install -y curl && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://ollama.com/install.sh | sh

ENV MODEL_NAME=granite4:350m
ENV OLLAMA_HOST=0.0.0.0:11434

EXPOSE 11434

RUN echo '#!/bin/bash\nset -e\nollama serve --host "${OLLAMA_HOST}" &\nSERVER_PID=$!\nsleep 15\nollama pull $MODEL_NAME\nwait $SERVER_PID' > /entrypoint.sh && \
    chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]


