# AI Ensemble System for k3s - Opus Asyncio Orchestrator
# Deploy with: kubectl apply -f opus_coordinator.yaml

---
# Promptimizer (Granite 4 350m model)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promptimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promptimizer
  template:
    metadata:
      labels:
        app: promptimizer
        ensemble: opus-ai-system
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            ensemble: opus-ai-system
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: promptimizer
        image: sebastein/promptimizer:v5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: promptimizer
spec:
  selector:
    app: promptimizer
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# LLaMA 3.2 1B model
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
        ensemble: opus-ai-system
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            ensemble: opus-ai-system
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: llama
        image: sebastein/llama:v5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1.5Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: llama
spec:
  selector:
    app: llama
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# Qwen 2.5 Coder 1.5B model
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen
  template:
    metadata:
      labels:
        app: qwen
        ensemble: opus-ai-system
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            ensemble: opus-ai-system
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: qwen
        image: sebastein/qwen:v5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "900m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: qwen
spec:
  selector:
    app: qwen
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# Qwen 3 0.6B model (Smallest)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-small
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen-small
  template:
    metadata:
      labels:
        app: qwen-small
        ensemble: opus-ai-system
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            ensemble: opus-ai-system
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: qwen-small
        image: sebastein/qwen_small:v5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-small
spec:
  selector:
    app: qwen-small
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# Judge (Gemma 3 1B model)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge
  template:
    metadata:
      labels:
        app: judge
        ensemble: opus-ai-system
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            ensemble: opus-ai-system
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: judge
        image: sebastein/judge:v5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1.5Gi"
            cpu: "900m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: judge
spec:
  selector:
    app: judge
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP

---
# Opus Asyncio Orchestrator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
        ensemble: opus-ai-system
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            ensemble: opus-ai-system
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      restartPolicy: Always
      initContainers:
      - name: wait-for-services
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          echo "Waiting for AI model services to be ready..."
          
          # Wait for all model services to respond
          until curl -f http://promptimizer:11434/api/tags 2>/dev/null; do 
            echo "Waiting for promptimizer..."; 
            sleep 5; 
          done
          
          until curl -f http://llama:11434/api/tags 2>/dev/null; do 
            echo "Waiting for llama..."; 
            sleep 5; 
          done
          
          until curl -f http://qwen:11434/api/tags 2>/dev/null; do 
            echo "Waiting for qwen..."; 
            sleep 5; 
          done
          
          until curl -f http://qwen-small:11434/api/tags 2>/dev/null; do 
            echo "Waiting for qwen-small..."; 
            sleep 5; 
          done
          
          until curl -f http://judge:11434/api/tags 2>/dev/null; do 
            echo "Waiting for judge..."; 
            sleep 5; 
          done
          
          echo "All model services responding! Giving models 30s more to fully load..."
          sleep 30
          echo "Ready to start opus asyncio orchestrator!"
      containers:
      - name: final-script-orchestrator
        image: sebastein/final_script:v6.0
        imagePullPolicy: Always
        stdin: true
        tty: true
        command: ["python", "/app/final_script.py"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
